version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/task-provider"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
