frontend:
- changed-files:
  - any-glob-to-any-file: 'task-app/**/*'
backend:
- changed-files:
  - any-glob-to-any-file: 'task-provider/**/*'
  - any-glob-to-any-file: 'task-consumer/**/*'
  - any-glob-to-any-file: 'pom.xml'
api:
  - changed-files:
      - any-glob-to-any-file: 'tasks-openapi.yaml'
openspec:
  - changed-files:
      - any-glob-to-any-file: 'openspec/**'
      - any-glob-to-any-file: 'AGENTS.md'
github:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
