name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

env:
  LC_ALL: en_US.UTF-8

jobs:
  BuildFrontend:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [ 22 ]
        os: [ ubuntu-latest ]
    name: Node ${{ matrix.node }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        shell: bash
        run: npm install --prefix ./task-app
      - name: Lint
        shell: bash
        run: npm run lint --prefix ./task-app
      - name: Build
        shell: bash
        run: npm run build --prefix ./task-app

  BuildBackend:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [ 22 ]
        java: [ 25 ]
        os: [ ubuntu-latest ]
    name: JDK${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v5
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build
      shell: bash
      run: mvn -V -U -e -ntp clean install
